#!/usr/bin/env python3

from pkg_resources import working_set
from subprocess import call


def up_pip():
    packages = [dist.project_name for dist in working_set]
    call("pip3 install --upgrade " + ' '.join(packages), shell=True)


if __name__ == '__main__':
    up_pip()
